//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracoesVETX.DAL.SQL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntegracoesVETX.DAL.SQL.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  DISTINCT  U.[U_CodRastreio] AS codigoRastreamento , R.CardCode AS cardCode , R.CardName AS nomeDestinatario , R.E_Mail AS emailDestinatario 
        ///, T2.Serial AS invoiceNumber , T0.DocNum AS docNPV  , T0.NumAtCard AS idOrderVtex  , T0.U_NumPedEXT AS idOrderVtex2 , T2.DocEntry AS docEntry  
        ///, T2.DocNum AS docNum 
        ///FROM    ORDR T0  
        ///INNER JOIN INV1 T1 ON T0.DocEntry = T1.BaseEntry   
        ///INNER JOIN OINV T2 ON T1.DocEntry = T2.DocEntry and T0.BPLId = T2.BPLId   
        ///INNER JOIN [SBO_TaxOne].[dbo].[Entidade] tax  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_BuscaCodRastreio {
            get {
                return ResourceManager.GetString("SAP_BuscaCodRastreio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT T0.DocNum AS docNPV ,T0.NumAtCard AS idOrderVtex , T0.U_NumPedEXT AS idOrderVtex2 
        ///,T2.DocEntry AS externalId ,T2.DocNum AS docSAP ,T2.Serial AS invoiceNumber ,T2.DocDate AS invoiceDate 
        ///,T3.KeyNfe AS nfeKey ,T0.PickRmrk AS shippingMethod ,T2.SeriesStr AS invoiceOrderSeries 
        ///,T1.ItemCode AS codItem ,T1.Price AS precoItem ,T1.Quantity AS qtdItem ,T2.DocTotal AS totalNF 
        ///FROM    ORDR T0 INNER JOIN INV1 T1 ON T0.DocEntry = T1.BaseEntry  
        ///INNER JOIN OINV T2 ON T1.DocEntry = T2.DocEntry and T0.BPLId  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SAP_DadosNF {
            get {
                return ResourceManager.GetString("SAP_DadosNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select top 1 Code, U_numVTEX From [@LOG_INTEGRACAO_VTEX] where U_numVTEX = &apos;{0}&apos; order by code desc.
        /// </summary>
        internal static string TblUser_BuscaIdLog {
            get {
                return ResourceManager.GetString("TblUser_BuscaIdLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE [@LOG_INTEGRACAO_VTEX] SET U_data = &apos;{0}&apos;, U_status = &apos;{1}&apos;, U_mensagem = &apos;{2}&apos;
        ///WHERE U_tipoDocumento = &apos;{3}&apos; AND U_numVTEX = &apos;{4}&apos; .
        /// </summary>
        internal static string TblUser_UpdateLog {
            get {
                return ResourceManager.GetString("TblUser_UpdateLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC SP_WAHL_PedidoVTEX_Adicionar &apos;{0}&apos;, &apos;{1}&apos;.
        /// </summary>
        internal static string VTEX_InserirPedido {
            get {
                return ResourceManager.GetString("VTEX_InserirPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select 
        ///	U_NUM_VTEX,
        ///	U_EVENTO
        ///from 
        ///	[@WAHL_VTEX_PEDIDOS] 
        ///where 
        ///	U_STATUS in (0,2) 
        ///order by
        ///	U_DATA .
        /// </summary>
        internal static string VTEX_PedidosIntegrar {
            get {
                return ResourceManager.GetString("VTEX_PedidosIntegrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC SP_WAHL_PedidoVTEX_Status &apos;{0}&apos;, &apos;{1}&apos;.
        /// </summary>
        internal static string VTEX_PedidoStatus {
            get {
                return ResourceManager.GetString("VTEX_PedidoStatus", resourceCulture);
            }
        }
    }
}
